### ISSUE TITLE
which already has a layout

### ISSUE THREAD

**Issue by omeranar1** [Arvind-4/qrcode-using-pyqt5#1]
`QLayout: Attempting to add QLayout "" to MainWindow "", which already has a layout
Traceback (most recent call last):
  File "D:\WORK\AKILLI TAHTA\qr.py", line 62, in generate_qr_code
    qr_image = qrcode.make(self.text, image_factory=Image).pixmap()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\omera\AppData\Local\Programs\Python\Python311\Lib\site-packages\qrcode\main.py", line 29, in make
    return qr.make_image()
           ^^^^^^^^^^^^^^^
  File "C:\Users\omera\AppData\Local\Programs\Python\Python311\Lib\site-packages\qrcode\main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'qrcode_modules'`

**Comment by arvind-4** [comment]
fixed it!
